### ISSUE TITLE
[Bug]: Fatal error with `copyDevPaths`

### ISSUE THREAD

**Issue by antonioeatgoat** [inpsyde/vip-composer-plugin#20]
### Description of the bug

It looks like the merge c84c73ce2392f57d5f1e31f0b60fe5b5a51c53bc introduced a bug.

Now the command `copyDevPath()` fails with a fatal error.

### Reproduction instructions

1. Update the package to the last version.
2. Try `composer vip --sync-dev-paths`.

### Expected behavior

The command is executed without any error.

### Relevant log output

```shell
The "/Users/mangiaca/Websites/project/vip-config/env" directory does not exist.

#0 /Users/mangiaca/Websites/project/vip/client-mu-plugins/vendor/inpsyde/vip-composer-plugin/src/Task/CopyDevPaths.php(189): Symfony\Component\Finder\Finder->in('/Users/mangiaca...')
#1 /Users/mangiaca/Websites/project/vip/client-mu-plugins/vendor/inpsyde/vip-composer-plugin/src/Task/CopyDevPaths.php(112): Inpsyde\VipComposer\Task\CopyDevPaths->pathInfoForKey('vip-config-dir')
#2 /Users/mangiaca/Websites/project/vip/client-mu-plugins/vendor/inpsyde/vip-composer-plugin/src/Task/CopyDevPaths.php(86): Inpsyde\VipComposer\Task\CopyDevPaths->copyDevPath('vip-config-dir', Object(Inpsyde\VipComposer\Io))
#3 /Users/mangiaca/Websites/project/vip/client-mu-plugins/vendor/inpsyde/vip-composer-plugin/src/Tasks.php(56): Inpsyde\VipComposer\Task\CopyDevPaths->run(Object(Inpsyde\VipComposer\Io), Object(Inpsyde\VipComposer\Task\TaskConfig))
#4 /Users/mangiaca/Websites/project/vip/client-mu-plugins/vendor/inpsyde/vip-composer-plugin/src/Command.php(185): Inpsyde\VipComposer\Tasks->run()
#5 phar:///opt/homebrew/Cellar/composer/2.6.6/bin/composer/vendor/symfony/console/Command/Command.php(298): Inpsyde\VipComposer\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///opt/homebrew/Cellar/composer/2.6.6/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///opt/homebrew/Cellar/composer/2.6.6/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Inpsyde\VipComposer\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///opt/homebrew/Cellar/composer/2.6.6/bin/composer/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///opt/homebrew/Cellar/composer/2.6.6/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///opt/homebrew/Cellar/composer/2.6.6/bin/composer/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///opt/homebrew/Cellar/composer/2.6.6/bin/composer/bin/composer(93): Composer\Console\Application->run()
#12 /opt/homebrew/Cellar/composer/2.6.6/bin/composer(29): require('phar:///opt/hom...')
#13 {main}

```
```


### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gmazzap** [comment]
I foundand fixed this in `development` branch, forgot to backport

**Comment by gmazzap** [comment]
@antonioeatgoat e9588b6 should have fixed it. Can you please test?

**Comment by antonioeatgoat** [comment]
@gmazzap I confirm that it works fine now. Thank you so much!

**Comment by gmazzap** [comment]
Thanks for confirming @antonioeatgoat. I release 2.0.0-beta.4 with the fix.
